import React from 'react';
import { Container, Card, Accordion, Alert } from 'react-bootstrap';
import logo from '../../assets/images/MPF-logo.svg';

const TermsAndConditions = () => {
    return (
        <Container className="my-5" style={{ maxWidth: '960px' }}>
            <div className="text-center mb-5">
                <img src={logo} alt="MyPathfinder logo" style={{maxWidth: 540, marginBottom: 28}}/>
                <h1 className="display-4 text-primary mb-3" style={{fontWeight: 700}}>Terms & Conditions</h1>
                <p className="lead text-muted">
                    Effective Date: 09/09/2025
                </p>
                <p className="text-muted">
                    Company: MyPathfinder Ltd ("MyPathfinder", "we", "us", "our")
                </p>
            </div>

            <Accordion defaultActiveKey="0" className="mb-4">
                <Accordion.Item eventKey="0">
                    <Accordion.Header>
                        <h5 className="mb-0">1. Definitions</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <dl className="row">
                            <dt className="col-sm-3">"Services"</dt>
                            <dd className="col-sm-9">
                                means the MyPathfinder online platform including CV tailoring,
                                job-matching, interview preparation, and related features.
                            </dd>

                            <dt className="col-sm-3">"User", "you", "your"</dt>
                            <dd className="col-sm-9">
                                refers to the individual accessing or using the Services.
                            </dd>

                            <dt className="col-sm-3">"Content"</dt>
                            <dd className="col-sm-9">
                                means all information, data, text, CVs, interview recordings,
                                or other material uploaded or generated by you.
                            </dd>
                        </dl>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="1">
                    <Accordion.Header>
                        <h5 className="mb-0">2. Eligibility</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <p>
                            You must be at least <strong>16 years old</strong> to use our Services.
                            By registering, you confirm you meet this requirement.
                        </p>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="2">
                    <Accordion.Header>
                        <h5 className="mb-0">3. Account Registration</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <ul className="list-unstyled">
                            <li className="mb-2">
                                <i className="bi bi-check-circle text-success me-2"></i>
                                You must provide accurate and complete information when creating an account.
                            </li>
                            <li className="mb-2">
                                <i className="bi bi-check-circle text-success me-2"></i>
                                You are responsible for safeguarding your login details.
                            </li>
                            <li className="mb-2">
                                <i className="bi bi-check-circle text-success me-2"></i>
                                You must notify us immediately if you suspect unauthorised use of your account.
                            </li>
                        </ul>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="3">
                    <Accordion.Header>
                        <h5 className="mb-0">4. Our Services</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <ul>
                            <li className="mb-2">
                                MyPathfinder provides career support tools powered by artificial intelligence.
                            </li>
                            <li className="mb-2">
                                While our Services are designed to enhance job applications and
                                interview readiness, <strong>we do not guarantee</strong> that use of the
                                Services will result in employment or job offers.
                            </li>
                            <li className="mb-2">
                                CVs, interview recordings, and other personal data are processed
                                according to our <strong>Privacy Policy</strong>.
                            </li>
                        </ul>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="4">
                    <Accordion.Header>
                        <h5 className="mb-0">5. User Obligations</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <p>When using MyPathfinder, you must not:</p>
                        <ul>
                            <li>Upload unlawful, offensive, discriminatory, or misleading content.</li>
                            <li>Attempt to interfere with the security or operation of the platform.</li>

                            <li>Share your account with others or impersonate another person.</li>
                            <li>Use the Services in a way that could damage our reputation or that of others.</li>
                        </ul>
                        <Alert variant="danger" className="mt-3">
                            <strong>Note:</strong> We reserve the right to suspend or terminate accounts in breach of these Terms.
                        </Alert>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="5">
                    <Accordion.Header>
                        <h5 className="mb-0">6. Subscriptions & Payments</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <ul className="list-unstyled">
                            <li className="mb-2">
                                <strong>Paid Services:</strong> Certain Services may require a paid subscription.
                                Pricing and duration will be displayed at the point of purchase.
                            </li>
                            <li className="mb-2">
                                <strong>Payment Processing:</strong> Payments are processed via Stripe.
                            </li>
                            <li className="mb-2">
                                <strong>Refunds:</strong> Refund and cancellation rights are set out in our
                                Refund & Cancellation Policy.
                            </li>
                            <li className="mb-2">
                                <strong>Access:</strong> Access to Services will be revoked if payment is not received.
                            </li>
                        </ul>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="6">
                    <Accordion.Header>
                        <h5 className="mb-0">7. Intellectual Property</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <div className="row">
                            <div className="col-md-6">
                                <Card className="h-100">
                                    <Card.Header className="bg-light">
                                        <strong>Our IP</strong>
                                    </Card.Header>
                                    <Card.Body>
                                        <p className="mb-0">
                                            All platform content, software, branding, and materials are owned by
                                            MyPathfinder or licensed to us.
                                        </p>
                                    </Card.Body>
                                </Card>
                            </div>
                            <div className="col-md-6">
                                <Card className="h-100">
                                    <Card.Header className="bg-light">
                                        <strong>Your Content</strong>
                                    </Card.Header>
                                    <Card.Body>
                                        <p className="mb-0">
                                            You retain ownership of your personal data and CV content, but grant
                                            MyPathfinder a limited licence to process and display it solely for
                                            delivering our Services.
                                        </p>
                                    </Card.Body>
                                </Card>
                            </div>
                        </div>
                        <Alert variant="info" className="mt-3">
                            <strong>Restriction:</strong> You may not copy, reproduce, or distribute any
                            part of our Services without prior written consent.
                        </Alert>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="7">
                    <Accordion.Header>
                        <h5 className="mb-0">8. Disclaimer of Warranties</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <ul>
                            <li className="mb-2">
                                Our Services are provided on an <strong>"as is" and "as available"</strong> basis.
                            </li>
                            <li className="mb-2">
                                We make no warranties that the Services will be error-free, uninterrupted,
                                or meet your specific expectations.
                            </li>
                            <li className="mb-2">
                                <strong>AI-generated outputs</strong> (including CV suggestions and interview feedback)
                                are recommendations only and should not be relied upon as professional or legal advice.
                            </li>
                        </ul>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="8">
                    <Accordion.Header>
                        <h5 className="mb-0">9. Limitation of Liability</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <p>To the fullest extent permitted by law:</p>
                        <ul>
                            <li className="mb-2">
                                MyPathfinder shall not be liable for indirect, incidental, or
                                consequential losses arising from your use of the Services.
                            </li>
                            <li className="mb-2">
                                Our total liability for any claim related to the Services shall not
                                exceed the total fees paid by you in the 12 months prior to the claim.
                            </li>
                            <li className="mb-2">
                                Nothing in these Terms excludes liability for death, personal injury,
                                or fraud caused by our negligence.
                            </li>
                        </ul>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="9">
                    <Accordion.Header>
                        <h5 className="mb-0">10. Termination</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <div className="row">
                            <div className="col-md-6">
                                <Card className="h-100 border-primary">
                                    <Card.Header className="bg-primary text-white">
                                        <strong>User Termination</strong>
                                    </Card.Header>
                                    <Card.Body>
                                        <p className="mb-0">
                                            You may terminate your account at any time via your account settings.
                                        </p>
                                    </Card.Body>
                                </Card>
                            </div>
                            <div className="col-md-6">
                                <Card className="h-100 border-warning">
                                    <Card.Header className="bg-warning text-dark">
                                        <strong>Company Termination</strong>
                                    </Card.Header>
                                    <Card.Body>
                                        <p className="mb-0">
                                            We may suspend or terminate access if you breach these Terms or misuse the Services.
                                        </p>
                                    </Card.Body>
                                </Card>
                            </div>
                        </div>
                        <Alert variant="secondary" className="mt-3">
                            <strong>Note:</strong> Termination does not affect rights and obligations accrued prior to termination.
                        </Alert>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="10">
                    <Accordion.Header>
                        <h5 className="mb-0">11. Governing Law & Jurisdiction</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <p>
                            These Terms are governed by the laws of <strong>England & Wales</strong>.
                            Disputes will be subject to the exclusive jurisdiction of the courts of
                            <strong> England & Wales</strong>.
                        </p>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="11">
                    <Accordion.Header>
                        <h5 className="mb-0">12. Contact Us</h5>
                    </Accordion.Header>
                    <Accordion.Body>
                        <Card>
                            <Card.Body>
                                <h6 className="card-title">For any queries relating to these Terms, please contact:</h6>
                                <address className="mb-0">
                                    <strong>MyPathfinder Ltd</strong><br />
                                    Email: <a href="mailto:hello@mypathfinder.uk" className="text-decoration-none">
                                        hello@mypathfinder.uk
                                    </a>
                                </address>
                            </Card.Body>
                        </Card>
                    </Accordion.Body>
                </Accordion.Item>
            </Accordion>

            <Card className="border-0 bg-light mt-4">
                <Card.Body className="text-center py-4">
                    <p className="text-muted mb-0">
                        &copy; {new Date().getFullYear()} MyPathfinder Ltd. All rights reserved.
                    </p>
                </Card.Body>
            </Card>
        </Container>
    );
};

export default TermsAndConditions;